apiVersion: v1
kind: Pod
metadata:
  name: bastion
spec:
  containers:
    - name: bastion
      image: "ubuntu:latest"
      command: ["sleep", "9999"]
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          cpu: 50m
          memory: 500Mi